CREATE TABLE payments (
   id BIGSERIAL PRIMARY KEY,
   order_id BIGINT NOT NULL REFERENCES orders(id),
   amount DECIMAL(10, 2) NOT NULL,
   status VARCHAR(20) NOT NULL,
   transaction_id VARCHAR(100),
   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);